services:
  - type: web
    name: om-caterers
    runtime: node
    region: oregon
    plan: starter
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    buildFilter:
      paths:
        - "**"
